spring:
  profiles:
    active:
      - dev

  flyway:
    enabled: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/cartdb
    username: postgres
    password:

goods:
  service:
    api:
      url: http://18.183.144.77:8080/goods

order:
  service:
    api:
      url: http://18.183.144.77:8081/orders

logging:
    level:
      org:
        hibernate:
          SQL: DEBUG