-- ----------------------------
-- Table structure for cart
-- ----------------------------
CREATE TABLE CART(
  CART_ID varchar(36),
  CUSTOMER_ID varchar(36),

  PRIMARY KEY (CART_ID)
);

COMMENT ON COLUMN CART.CART_ID IS '購物車ID';
COMMENT ON COLUMN CART.CUSTOMER_ID IS '消費者ID';

COMMENT ON TABLE CART IS '購物車';

-- ----------------------------
-- Table structure for customer
-- ----------------------------
CREATE TABLE CUSTOMER(
  CUSTOMER_ID varchar(36),
  CUSTOMER_NAME varchar(30),

  PRIMARY KEY (CUSTOMER_ID)
);

COMMENT ON COLUMN CUSTOMER.CUSTOMER_ID IS '消費者ID';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_NAME IS '消費者名稱';

COMMENT ON TABLE CUSTOMER IS '消費者';

-- ----------------------------
-- Table structure for cart_list
-- ----------------------------
CREATE TABLE CART_LIST(
  CART_ID varchar(36),
  GOODS_ID varchar(60),
  GOODS_NAME varchar(60),
  GOODS_COUNT int,
  GOODS_UNIT_PRICE int,

  PRIMARY KEY (CART_ID, GOODS_ID)
);

COMMENT ON COLUMN CART_LIST.CART_ID IS '購物車ID';
COMMENT ON COLUMN CART_LIST.GOODS_ID IS '商品ID';
COMMENT ON COLUMN CART_LIST.GOODS_NAME IS '商品名稱';
COMMENT ON COLUMN CART_LIST.GOODS_COUNT IS '商品數量';
COMMENT ON COLUMN CART_LIST.GOODS_UNIT_PRICE IS '商品單價';

COMMENT ON TABLE CUSTOMER IS '購物車清單';

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME) VALUES ('e92e3295-b305-4c02-b995-67effaf7cff6', '測試客戶');
INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME) VALUES ('924f436c-d9d4-4a80-ae2a-367b090d7b8d', '測試客戶1');

INSERT INTO CART (CART_ID, CUSTOMER_ID) VALUES ('8e67f8e4-4312-4093-9886-0f7f704a3f50', '924f436c-d9d4-4a80-ae2a-367b090d7b8d');

INSERT INTO CART_LIST (CART_ID, GOODS_ID, GOODS_NAME, GOODS_COUNT, GOODS_UNIT_PRICE)
VALUES ('8e67f8e4-4312-4093-9886-0f7f704a3f50', '8762289', '【股癌新作】灰階思考', 6, 316);
